# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-16 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='static/img/user.png', upload_to='avatar/'),
        ),
    ]
