# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-24 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190318_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2019-02-21'),
            preserve_default=False,
        ),
    ]
